---
- name: Install and start nginx webserver
  hosts: webserver
  tasks:
    - name: install nginx server
      apt:
        name: nginx
        state: latest
      become: yes
    - name: start nginx service
      service:
        name: nginx
        state: started
      become: yes
