---
- name: Stop and remove nginx webserver
  hosts: webserver
  become: yes
  tasks:
    - name: stop nginx service
      service:
        name: nginx
        state: stopped    
    - name: uninstall nginx server
      apt:
        name: nginx
        state: absent
        autoremove: true
        purge: true        
      

