---
- name: Configure nginx webserver
  hosts: webserver
  tasks:
    - name: stop nginx
      service:
        name: nginx
        state: stopped
      become: yes    
    - name: uninstall nginx server
      apt:
        name: nginx=1.18*
        state: absent
      become: yes

