---
- name: Update repos and install docker and stuff on aws ec2
  hosts: ansdok
  become: yes
  tasks:
    - name: Update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_only: yes
    - name: Ensure net-tools, acl, docker and docker-compose are installed
      ansible.builtin.yum:
        name:
          - net-tools
          - acl
          - docker
        state: present
        update_cache: yes
    - name: Start docker and Enable Docker service at startup
      service:
        name: docker
        state: started
        enabled: yes
    - name: Ensure docker-compose standalone is installed on the server
      ansible.builtin.get_url:
        # using Jinja2 builtin plugin lookup to get system architecture with 'uname -m'
        url: https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/libexec/docker/cli-plugins/docker-compose
        mode: +x
    #install docker python to use ansible.community docker modules
    - name: Ensure docker python module is installed
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose        