---
- name: Update repos and install docker and stuff on aws ec2
  hosts: ansdok
  become: yes
  tasks:
    - name: Update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_only: yes
    - name: Ensure net-tools, acl, docker and docker-compose are installed
      ansible.builtin.yum:
        name:
          - net-tools
          - acl
          - docker
        state: present
        update_cache: yes