---

- name: Login to docker private repo
  community.docker.docker_login:
    registry_url: https://index.docker.io/v1/miltosdev/my-private-repo
    username: miltosdev
    password: "{{docker_pass}}"
    
- name: Copy docker-compose.yml to server
  ansible.builtin.copy:
    src: /home/mltamd/learn/ansible/learn-ansible/docker-compose.yml
    dest: /home/mlt/docker-compose.yml
    # owner: ec2-user
    # group: ec2-user

- name: Start containers with compose
  community.docker.docker_compose:
    project_src: /home/mlt/
    state: present