version: '3'
services:
    my-app:
        #image: 999339999999.dkr.ecr.eu-central-1.amazonaws.com/my-app:1.3
        #image: ${aws_ecr}/my-app:1.3
        image: miltosdev/my-private-repo:jma2-v-1.0.0
        ports:
            - 3000:3000
        container_name: jma2v100app
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db
    mongo-express:
        image: mongo-express
        ports:
            - 8080:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb
        depends_on:
            - "mongodb"
        restart: unless-stopped

volumes:
    mongo-data:
        driver: local
