plugin: aws_ec2
regions:
  - eu-west-3
filters:
  # All instances with their `Environment` tag set to `dev`
  tag:Name: node
keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type
