---
- name: Install python3, docker, docker-compose
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars:
        #in case python3 is not installed
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        #use_backend: dnf
        name:
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Ensure docker-compose standalone is installed on the server
      ansible.builtin.get_url:
        # using Jinja2 builtin plugin lookup to get system architecture with 'uname -m'
        # https://github.com/docker/compose
        url: https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker and Enable Docker service at startup
      service:
        name: docker
        state: started
        enabled: yes
    #install docker python to use ansible.community docker modules
    - name: Ensure docker python module is installed
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose

- name: Ensure ec2-user can run docker commands without sudo
  hosts: all
  become: yes
  tasks:
    # add ec2-user to docker group to run docker commands without sudo
    # prefer user module instead of shell module
    # APPEND so we don't remove user from other groups
    - name: Add ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes
    # reset connection so ec2-user gets the newly assigned group
    - name: Reconnect to server
      meta: reset_connection