---
- name: Install docker
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install docker
      yum:
        name:
          - docker
        update_cache: yes
        state: present
    - name: Start docker and Enable Docker service at startup
      service:
        name: docker
        state: started
        enabled: yes

- name: Ensure ec2-user can run docker commands without sudo
  hosts: all
  become: yes
  tasks:
    # add ec2-user to docker group to run docker commands without sudo
    # prefer user module instead of shell module
    # append so we don't remove user from other groups
    - name: Add ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes
    # reset connection so ec2-user gets the newly assigned group
    - name: Reconnect to server
      meta: reset_connection
    - name: Show system info
      ansible.builtin.command: uname -a


